import { OptionSchema } from "../interfaces/fields.interface";
import { schemas } from "chaca";

export const ImageOptions: OptionSchema[] = [
  {
    name: "Animal",
    getValue: schemas.image.animal().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.image.animal().getValue(),
    arguments: [],
  },
  {
    name: "Architecture",
    getValue: schemas.image.architecture().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.image.architecture().getValue(),
    arguments: [],
  },
  {
    name: "Art",
    getValue: schemas.image.art().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.image.art().getValue(),
    arguments: [],
  },
  {
    name: "Event",
    getValue: schemas.image.event().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.image.event().getValue(),
    arguments: [],
  },
  {
    name: "Fashion",
    getValue: schemas.image.fashion().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.image.fashion().getValue(),
    arguments: [],
  },
  {
    name: "Film",
    getValue: schemas.image.film().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.image.film().getValue(),
    arguments: [],
  },
  {
    name: "Food",
    getValue: schemas.image.food().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.image.food().getValue(),
    arguments: [],
  },
  {
    name: "Health",
    getValue: schemas.image.health().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.image.health().getValue(),
    arguments: [],
  },
  {
    name: "History",
    getValue: schemas.image.history().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.image.history().getValue(),
    arguments: [],
  },
  {
    name: "House",
    getValue: schemas.image.house().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.image.house().getValue(),
    arguments: [],
  },
  {
    name: "Nature",
    getValue: schemas.image.nature().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.image.nature().getValue(),
    arguments: [],
  },
  {
    name: "People",
    getValue: schemas.image.people().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.image.people().getValue(),
    arguments: [],
  },
  {
    name: "Spiritual",
    getValue: schemas.image.spiritual().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.image.spiritual().getValue(),
    arguments: [],
  },
  {
    name: "Sport",
    getValue: schemas.image.sport().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.image.sport().getValue(),
    arguments: [],
  },
  {
    name: "Street",
    getValue: schemas.image.street().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.image.street().getValue(),
    arguments: [],
  },
  {
    name: "Travel",
    getValue: schemas.image.travel().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.image.travel().getValue(),
    arguments: [],
  },
  {
    name: "3D",
    getValue: schemas.image.treeDimension().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.image.treeDimension().getValue(),
    arguments: [],
  },
  {
    name: "Wallpaper",
    getValue: schemas.image.wallpaper().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.image.wallpaper().getValue(),
    arguments: [],
  },
  {
    name: "Animate Avatar",
    exampleValue: schemas.image.animateAvatar().getValue(),
    getValue: schemas.image.animateAvatar().getValue,
    arguments: [],
    description: { en: "", es: "" },
  },
];
