import { schemas } from "chaca";
import { OptionSchema } from "../interfaces/fields.interface";

export const VideoOptions: OptionSchema[] = [
  {
    name: "Animal",
    getValue: schemas.video.animal().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.video.animal().getValue(),
    arguments: [],
  },
  {
    name: "Architecture",
    getValue: schemas.video.architecture().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.video.architecture().getValue(),
    arguments: [],
  },
  {
    name: "Art",
    getValue: schemas.video.art().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.video.art().getValue(),
    arguments: [],
  },
  {
    name: "Event",
    getValue: schemas.video.event().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.video.event().getValue(),
    arguments: [],
  },
  {
    name: "Fashion",
    getValue: schemas.video.fashion().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.video.fashion().getValue(),
    arguments: [],
  },
  {
    name: "Food",
    getValue: schemas.video.food().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.video.food().getValue(),
    arguments: [],
  },
  {
    name: "Health",
    getValue: schemas.video.health().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.video.health().getValue(),
    arguments: [],
  },
  {
    name: "History",
    getValue: schemas.video.history().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.video.history().getValue(),
    arguments: [],
  },
  {
    name: "Nature",
    getValue: schemas.video.nature().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.video.nature().getValue(),
    arguments: [],
  },
  {
    name: "People",
    getValue: schemas.video.people().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.video.people().getValue(),
    arguments: [],
  },
  {
    name: "Spiritual",
    getValue: schemas.video.spiritual().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.video.spiritual().getValue(),
    arguments: [],
  },
  {
    name: "Sport",
    getValue: schemas.video.sport().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.video.sport().getValue(),
    arguments: [],
  },
  {
    name: "Street",
    getValue: schemas.video.street().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.video.street().getValue(),
    arguments: [],
  },
  {
    name: "Travel",
    getValue: schemas.video.travel().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.video.travel().getValue(),
    arguments: [],
  },
  {
    name: "3D",
    getValue: schemas.video.treeDimension().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.video.treeDimension().getValue(),
    arguments: [],
  },
  {
    name: "Wallpaper",
    getValue: schemas.video.wallpaper().getValue,
    description: { en: "", es: "" },
    exampleValue: schemas.video.wallpaper().getValue(),
    arguments: [],
  },
];
